import React from 'react'
import { Document, Page, Text, View, StyleSheet, Font } from '@react-pdf/renderer'

Font.register({
  family: 'Inter',
  fonts: [
    { src: 'https://fonts.gstatic.com/s/inter/v13/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuLyfAZ9hiJ-Ek-_EeA.woff', fontWeight: 400 },
    { src: 'https://fonts.gstatic.com/s/inter/v13/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuGKYAZ9hiJ-Ek-_EeA.woff', fontWeight: 700 },
  ],
})

const styles = StyleSheet.create({
  page: {
    paddingTop: 48,
    paddingBottom: 60,
    paddingHorizontal: 48,
    backgroundColor: '#FFFFFF',
    fontFamily: 'Inter',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 32,
    paddingBottom: 20,
    borderBottomWidth: 2,
    borderBottomColor: '#00D4A0',
  },
  logoArea: { flexDirection: 'column' },
  logoText: {
    fontSize: 18,
    fontWeight: 700,
    color: '#0A0F1A',
    letterSpacing: 1,
  },
  tagline: {
    fontSize: 9,
    color: '#6B8299',
    marginTop: 2,
    letterSpacing: 0.5,
  },
  dateArea: { alignItems: 'flex-end' },
  dateLabel: { fontSize: 9, color: '#6B8299' },
  dateValue: { fontSize: 11, color: '#0A0F1A', marginTop: 2 },
  body: { marginTop: 8 },
  paragraph: {
    fontSize: 11,
    lineHeight: 1.7,
    color: '#1A202C',
    marginBottom: 12,
  },
  footer: {
    position: 'absolute',
    bottom: 24,
    left: 48,
    right: 48,
    borderTopWidth: 1,
    borderTopColor: '#E2E8F0',
    paddingTop: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  footerText: {
    fontSize: 8,
    color: '#9BAFC4',
  },
})

interface AppealLetterProps {
  content: string
  date: string
}

export function AppealLetterDocument({ content, date }: AppealLetterProps) {
  // Strip the "APPEAL LETTER:" prefix if present
  const cleanContent = content.replace(/^APPEAL LETTER:\s*/i, '').trim()
  const paragraphs = cleanContent.split('\n').filter((p) => p.trim())

  return React.createElement(
    Document,
    { title: 'Appeal Letter — CodeMed AI' },
    React.createElement(
      Page,
      { size: 'LETTER', style: styles.page },
      React.createElement(
        View,
        { style: styles.header },
        React.createElement(
          View,
          { style: styles.logoArea },
          React.createElement(Text, { style: styles.logoText }, 'CODEMED'),
          React.createElement(
            Text,
            { style: styles.tagline },
            'AI Revenue Cycle Intelligence for Healthcare · codemedgroup.com'
          )
        ),
        React.createElement(
          View,
          { style: styles.dateArea },
          React.createElement(Text, { style: styles.dateLabel }, 'Date'),
          React.createElement(Text, { style: styles.dateValue }, date)
        )
      ),
      React.createElement(
        View,
        { style: styles.body },
        ...paragraphs.map((para, idx) =>
          React.createElement(
            Text,
            { key: idx, style: styles.paragraph },
            para
          )
        )
      ),
      React.createElement(
        View,
        { style: styles.footer, fixed: true },
        React.createElement(
          Text,
          { style: styles.footerText },
          'Generated by CodeMed AI · codemedgroup.com'
        ),
        React.createElement(
          Text,
          { style: styles.footerText },
          'Review before submission — Not a substitute for clinical judgment'
        )
      )
    )
  )
}
